
cc_binary(
    name = 'mysql',
    srcs = ['mysql.cpp'],
    deps = ['//:libodbcxx'],
)

cc_binary(
    name = 'scroll',
    srcs = ['scroll.cpp'],
    deps = ['//:libodbcxx'],
)

cc_binary(
    name = 'dmtest',
    srcs = ['dmtest.cpp'],
    deps = ['//:libodbcxx'],
)

cc_binary(
    name = 'streams',
    srcs = ['streams.cpp'],
    deps = ['//:libodbcxx'],
)

cc_binary(
    name = 'dbmetadata',
    srcs = ['dbmetadata.cpp'],
    deps = ['//:libodbcxx'],
)

cc_binary(
    name = 'oracle',
    srcs = ['oracle.cpp'],
    deps = ['//:libodbcxx'],
)
